[project]
name = "cree-agentes-usando-foundry"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Eduardo-cod", email = "eduardoesparza97@hotmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "azure-identity>=1.25.3",
    "dotenv>=0.9.9",
    "openai>=3.14.1",
]

[project.scripts]
cree-agentes-usando-foundry = "cree_agentes_usando_foundry:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
